[build]
builder = "RAILPACK"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Volume pour la persistance de la base de donn√©es SQLite
[[volumes]]
name = "database"
mountPath = "/app/data"
